/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adopsiHewan.view;

import adopsiHewan.controller.DashboardAdminController;
import adopsiHewan.config.DBConnection;

import javax.swing.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
/**
 *
 * @author ASUS
 */
public class DashboardAdminView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdminView
     */
    
    DashboardAdminController dba;
    DBConnection con;
    LocalDate tanggal = LocalDate.now();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy", new Locale("id", "ID"));
    String tanggalFormatted = tanggal.format(formatter);
    
    public DashboardAdminView() {
        initComponents();
        dba = new DashboardAdminController(this);
        dba.tampilkanData();
        dba.tampilkanGambar1();
        dba.tampilkanGambar2();
        txtTanggal.setText(tanggalFormatted);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJudulPage = new javax.swing.JLabel();
        txtJudulJH = new javax.swing.JLabel();
        txtJudulJD = new javax.swing.JLabel();
        txtJudulJU = new javax.swing.JLabel();
        titikDua1 = new javax.swing.JLabel();
        titikDua2 = new javax.swing.JLabel();
        titikDua3 = new javax.swing.JLabel();
        txtHewanMasuk = new javax.swing.JLabel();
        txtHewanDiadopsi = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JLabel();
        gambar1 = new javax.swing.JLabel();
        gambar2 = new javax.swing.JLabel();
        txtJmlHewan = new javax.swing.JLabel();
        txtJmlDiadopsi = new javax.swing.JLabel();
        txtJmlUser = new javax.swing.JLabel();
        txtNamaMasuk = new javax.swing.JLabel();
        txtNamaDiadopsi = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        btnManajemenHewan = new javax.swing.JButton();
        btnManajemenAdopsi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtJudulPage.setText("DASHBOARD");

        txtJudulJH.setText("Jumlah Hewan");

        txtJudulJD.setText("Jumlah Diadopsi");

        txtJudulJU.setText("Jumlah User");

        titikDua1.setText(":");

        titikDua2.setText(":");

        titikDua3.setText(":");

        txtHewanMasuk.setText("Hewan baru masuk");

        txtHewanDiadopsi.setText("Hewan baru diadopsi");

        txtTanggal.setText("tanggal");

        gambar1.setText("gambar1.jpg");

        gambar2.setText("gambar2.jpg");

        txtJmlHewan.setText("...");

        txtJmlDiadopsi.setText("...");

        txtJmlUser.setText("...");

        txtNamaMasuk.setText("nama masuk");

        txtNamaDiadopsi.setText("nama diadopsi");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btnDashboard.setText("Dashboard");

        btnRiwayat.setText("Riwayat");

        btnManajemenHewan.setText("Manajemen Hewan");

        btnManajemenAdopsi.setText("Manajemen Adopsi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDashboard)
                .addGap(18, 18, 18)
                .addComponent(btnManajemenHewan)
                .addGap(18, 18, 18)
                .addComponent(btnManajemenAdopsi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRiwayat)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDashboard)
                    .addComponent(btnRiwayat)
                    .addComponent(btnManajemenHewan)
                    .addComponent(btnManajemenAdopsi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtJudulJH)
                        .addGap(18, 18, 18)
                        .addComponent(titikDua1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtJmlHewan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtJudulJU, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(titikDua3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtJmlUser, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtJudulJD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titikDua2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtJmlDiadopsi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtHewanMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gambar1)
                        .addComponent(txtNamaMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtHewanDiadopsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gambar2)
                        .addComponent(txtNamaDiadopsi, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(529, 529, 529)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtJudulPage)
                    .addComponent(txtTanggal))
                .addContainerGap(560, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtJudulPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTanggal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHewanMasuk)
                                .addGap(18, 18, 18)
                                .addComponent(gambar1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJudulJH)
                                    .addComponent(titikDua1)
                                    .addComponent(txtJmlHewan))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJudulJD)
                                    .addComponent(titikDua2)
                                    .addComponent(txtJmlDiadopsi))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJudulJU)
                                    .addComponent(titikDua3)
                                    .addComponent(txtJmlUser))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaMasuk)
                        .addGap(98, 98, 98)
                        .addComponent(txtHewanDiadopsi)
                        .addGap(18, 18, 18)
                        .addComponent(gambar2)
                        .addGap(37, 37, 37)
                        .addComponent(txtNamaDiadopsi)
                        .addGap(0, 192, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DBConnection.getConnection();
                new DashboardAdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnManajemenAdopsi;
    private javax.swing.JButton btnManajemenHewan;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JLabel gambar1;
    private javax.swing.JLabel gambar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titikDua1;
    private javax.swing.JLabel titikDua2;
    private javax.swing.JLabel titikDua3;
    private javax.swing.JLabel txtHewanDiadopsi;
    private javax.swing.JLabel txtHewanMasuk;
    private javax.swing.JLabel txtJmlDiadopsi;
    private javax.swing.JLabel txtJmlHewan;
    private javax.swing.JLabel txtJmlUser;
    private javax.swing.JLabel txtJudulJD;
    private javax.swing.JLabel txtJudulJH;
    private javax.swing.JLabel txtJudulJU;
    private javax.swing.JLabel txtJudulPage;
    private javax.swing.JLabel txtNamaDiadopsi;
    private javax.swing.JLabel txtNamaMasuk;
    private javax.swing.JLabel txtTanggal;
    // End of variables declaration//GEN-END:variables

    public JLabel getTxtJmlHewan() {
        return txtJmlHewan;
    }
    
    public JLabel getTxtJmlDiadopsi() {
        return txtJmlDiadopsi;
    }
    
    public JLabel getTxtJmlUser() {
        return txtJmlUser;
    }
    
    public JLabel getTxtNamaMasuk() {
        return txtNamaMasuk;
    }
    
    public JLabel getTxtNamaDiadopsi() {
        return txtNamaDiadopsi;
    }
    
    public JLabel getGambar1() {
        return gambar1;
    }
    
    public JLabel getGambar2() {
        return gambar2;
    }
}
