/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adopsiHewan.view;

import adopsiHewan.controller.DashboardAdminController;
import adopsiHewan.config.DBConnection;

import javax.swing.*;
/**
 *
 * @author ASUS
 */
public class DashboardAdminView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdminView
     */
    
    DashboardAdminController dba;
    DBConnection con;
    
    public DashboardAdminView() {
        initComponents();
        dba = new DashboardAdminController(this);
        dba.tampilkanData();
        dba.tampilkanGambar1();
        dba.tampilkanGambar2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDashboard = new javax.swing.JButton();
        btnManajemenHewan = new javax.swing.JButton();
        btnManajemenAdopsi = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        txtJudulPage = new javax.swing.JLabel();
        txtJudulJH = new javax.swing.JLabel();
        txtJudulJD = new javax.swing.JLabel();
        txtJudulJU = new javax.swing.JLabel();
        titikDua1 = new javax.swing.JLabel();
        titikDua2 = new javax.swing.JLabel();
        titikDua3 = new javax.swing.JLabel();
        txtHewanMasuk = new javax.swing.JLabel();
        txtHewanDiadopsi = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JLabel();
        txtJmlHewan = new javax.swing.JTextField();
        txtJmlDiadopsi = new javax.swing.JTextField();
        txtJmlUser = new javax.swing.JTextField();
        txtNamaMasuk = new javax.swing.JTextField();
        txtNamaDiadopsi = new javax.swing.JTextField();
        gambar1 = new javax.swing.JLabel();
        gambar2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDashboard.setText("Dashboard");

        btnManajemenHewan.setText("Manajemen Hewan");

        btnManajemenAdopsi.setText("Manajemen Adopsi");

        btnRiwayat.setText("Riwayat");

        txtJudulPage.setText("DASHBOARD");

        txtJudulJH.setText("Jumlah Hewan");

        txtJudulJD.setText("Jumlah Diadopsi");

        txtJudulJU.setText("Jumlah User");

        titikDua1.setText(":");

        titikDua2.setText(":");

        titikDua3.setText(":");

        txtHewanMasuk.setText("Hewan baru masuk");

        txtHewanDiadopsi.setText("Hewan baru diadopsi");

        txtTanggal.setText("tanggal");

        txtJmlHewan.setText("...");

        txtJmlDiadopsi.setText("...");

        txtJmlUser.setText("...");

        txtNamaMasuk.setText("...");

        txtNamaDiadopsi.setText("...");

        gambar1.setText("gambar1.jpg");

        gambar2.setText("gambar2.jpg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtJudulJU, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(titikDua3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtJmlUser, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtJudulJD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnManajemenHewan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnManajemenAdopsi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRiwayat))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(titikDua2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtJmlDiadopsi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtJudulJH)
                                .addGap(18, 18, 18)
                                .addComponent(titikDua1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtJmlHewan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(339, 339, 339)
                                .addComponent(txtJudulPage))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHewanMasuk)
                                            .addComponent(gambar1))
                                        .addGap(132, 132, 132)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHewanDiadopsi)
                                            .addComponent(gambar2)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtNamaMasuk)
                                            .addGap(132, 132, 132)
                                            .addComponent(txtNamaDiadopsi))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(139, 139, 139)
                                            .addComponent(txtTanggal)
                                            .addGap(167, 167, 167))))))
                        .addGap(0, 177, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDashboard)
                    .addComponent(btnManajemenHewan)
                    .addComponent(btnManajemenAdopsi)
                    .addComponent(btnRiwayat))
                .addGap(18, 18, 18)
                .addComponent(txtJudulPage)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJudulJH)
                    .addComponent(titikDua1)
                    .addComponent(txtJmlHewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJudulJD)
                    .addComponent(titikDua2)
                    .addComponent(txtJmlDiadopsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJudulJU)
                    .addComponent(titikDua3)
                    .addComponent(txtJmlUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHewanMasuk)
                    .addComponent(txtHewanDiadopsi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gambar1)
                    .addComponent(gambar2))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaDiadopsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(txtTanggal)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DBConnection.getConnection();
                new DashboardAdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnManajemenAdopsi;
    private javax.swing.JButton btnManajemenHewan;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JLabel gambar1;
    private javax.swing.JLabel gambar2;
    private javax.swing.JLabel titikDua1;
    private javax.swing.JLabel titikDua2;
    private javax.swing.JLabel titikDua3;
    private javax.swing.JLabel txtHewanDiadopsi;
    private javax.swing.JLabel txtHewanMasuk;
    private javax.swing.JTextField txtJmlDiadopsi;
    private javax.swing.JTextField txtJmlHewan;
    private javax.swing.JTextField txtJmlUser;
    private javax.swing.JLabel txtJudulJD;
    private javax.swing.JLabel txtJudulJH;
    private javax.swing.JLabel txtJudulJU;
    private javax.swing.JLabel txtJudulPage;
    private javax.swing.JTextField txtNamaDiadopsi;
    private javax.swing.JTextField txtNamaMasuk;
    private javax.swing.JLabel txtTanggal;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtJmlHewan() {
        return txtJmlHewan;
    }
    
    public JTextField getTxtJmlDiadopsi() {
        return txtJmlDiadopsi;
    }
    
    public JTextField getTxtJmlUser() {
        return txtJmlUser;
    }
    
    public JTextField getTxtNamaMasuk() {
        return txtNamaMasuk;
    }
    
    public JTextField getTxtNamaDiadopsi() {
        return txtNamaDiadopsi;
    }
    
    public JLabel getGambar1() {
        return gambar1;
    }
    
    public JLabel getGambar2() {
        return gambar2;
    }
}
