/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adopsiHewan.view;

import javax.swing.*;
import adopsiHewan.controller.ManajemenHewanController;
import adopsiHewan.util.PhotoHandler;
import adopsiHewan.view.DashboardAdminView;
import adopsiHewan.view.ManajemenAdopsi;
import adopsiHewan.view.RiwayatAdopsiView;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.awt.*;
import java.awt.event.*;
import java.util.List;

/**
 *
 * @author ASUS
 */
public class ManajemenHewanView extends javax.swing.JFrame {
    
    ManajemenHewanController mhc;
    DashboardAdminView dav;
    ManajemenAdopsi mav;
    RiwayatAdopsiView rav;
    PhotoHandler ph;
    
    /**
     * Creates new form ManajemenHewanView
     */
    public ManajemenHewanView() {
        initComponents();
        mhc = new ManajemenHewanController(this);
        ph = new PhotoHandler();
        mhc.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulID = new javax.swing.JLabel();
        judulNama = new javax.swing.JLabel();
        judulJenis = new javax.swing.JLabel();
        judulUmur = new javax.swing.JLabel();
        judulKelamin = new javax.swing.JLabel();
        judulDeskripsi = new javax.swing.JLabel();
        judulFoto = new javax.swing.JLabel();
        judulStatus = new javax.swing.JLabel();
        titikDua1 = new javax.swing.JLabel();
        titikDua2 = new javax.swing.JLabel();
        titikDua3 = new javax.swing.JLabel();
        titikDua4 = new javax.swing.JLabel();
        titikDua5 = new javax.swing.JLabel();
        titikDua6 = new javax.swing.JLabel();
        titikDua7 = new javax.swing.JLabel();
        titikDua8 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtUmur = new javax.swing.JTextField();
        txtDeskripsi = new javax.swing.JTextField();
        setJenis = new javax.swing.JComboBox<>();
        setKelamin = new javax.swing.JComboBox<>();
        fotoHewan = new javax.swing.JLabel();
        setStatus = new javax.swing.JComboBox<>();
        judulSearch = new javax.swing.JLabel();
        txtCariNama = new javax.swing.JTextField();
        buttonCariNama = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        buttonInsert = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        judulBulan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        judulHalaman = new javax.swing.JLabel();
        buttonDashboard = new javax.swing.JButton();
        buttonManajemenHewan = new javax.swing.JButton();
        buttonManajemenAdopsi = new javax.swing.JButton();
        buttonRiwayat = new javax.swing.JButton();
        buttonPilihFoto = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judulID.setText("ID");

        judulNama.setText("Nama");

        judulJenis.setText("Jenis");

        judulUmur.setText("Umur");

        judulKelamin.setText("Kelamin");

        judulDeskripsi.setText("Deskripsi");

        judulFoto.setText("Foto");

        judulStatus.setText("Status");

        titikDua1.setText(":");

        titikDua2.setText(":");

        titikDua3.setText(":");

        titikDua4.setText(":");

        titikDua5.setText(":");

        titikDua6.setText(":");

        titikDua7.setText(":");

        titikDua8.setText(":");

        setJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anjing", "Kucing" }));

        setKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jantan", "Betina" }));

        fotoHewan.setText("fotoHewan.jpg");

        setStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Diadopsi", "Sudah Diadopsi" }));

        judulSearch.setText("Cari Hewan");

        txtCariNama.setText("nama hewan...");
        txtCariNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCariNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCariNamaFocusLost(evt);
            }
        });

        buttonCariNama.setText("cari");
        buttonCariNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariNamaActionPerformed(evt);
            }
        });

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tabelData);

        buttonInsert.setText("simpan");
        buttonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertActionPerformed(evt);
            }
        });

        buttonUpdate.setText("ubah");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonDelete.setText("hapus");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonReset.setText("batal");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        judulBulan.setText("bulan");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setToolTipText("");

        judulHalaman.setBackground(new java.awt.Color(204, 204, 204));
        judulHalaman.setForeground(new java.awt.Color(255, 255, 255));
        judulHalaman.setText("MANAJEMEN HEWAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judulHalaman)
                .addGap(551, 551, 551))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulHalaman)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        buttonDashboard.setText("Dashboard");
        buttonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDashboardActionPerformed(evt);
            }
        });

        buttonManajemenHewan.setText("Manajemen Hewan");

        buttonManajemenAdopsi.setText("Manajemen Adopsi");
        buttonManajemenAdopsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManajemenAdopsiActionPerformed(evt);
            }
        });

        buttonRiwayat.setText("Riwayat");
        buttonRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRiwayatActionPerformed(evt);
            }
        });

        buttonPilihFoto.setText("pilih foto");
        buttonPilihFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPilihFotoActionPerformed(evt);
            }
        });

        buttonRefresh.setText("segarkan");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(judulID, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titikDua1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonInsert)
                                .addGap(22, 22, 22)
                                .addComponent(buttonUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(buttonDelete)
                                .addGap(18, 18, 18)
                                .addComponent(buttonReset))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(judulDeskripsi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(judulKelamin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(judulUmur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(judulJenis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(judulNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(titikDua6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(titikDua5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(titikDua4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(titikDua3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(titikDua2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(setKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(setJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(judulBulan))
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(judulStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(judulFoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(titikDua7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titikDua8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(setStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fotoHewan)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonPilihFoto)))))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(judulSearch)
                                .addGap(18, 18, 18)
                                .addComponent(txtCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(buttonDashboard)
                        .addGap(18, 18, 18)
                        .addComponent(buttonManajemenHewan)
                        .addGap(18, 18, 18)
                        .addComponent(buttonManajemenAdopsi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonRiwayat))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonRefresh)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDashboard)
                    .addComponent(buttonManajemenHewan)
                    .addComponent(buttonManajemenAdopsi)
                    .addComponent(buttonRiwayat))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(judulSearch)
                            .addComponent(txtCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCariNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(buttonRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(judulID)
                            .addComponent(titikDua1)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(judulNama)
                            .addComponent(titikDua2)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(judulJenis)
                            .addComponent(titikDua3)
                            .addComponent(setJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(judulUmur)
                            .addComponent(titikDua4)
                            .addComponent(txtUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(judulBulan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(judulKelamin)
                            .addComponent(titikDua5)
                            .addComponent(setKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(judulDeskripsi)
                                .addComponent(titikDua6))
                            .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(judulFoto)
                            .addComponent(fotoHewan)
                            .addComponent(titikDua7)
                            .addComponent(buttonPilihFoto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(judulStatus)
                            .addComponent(titikDua8)
                            .addComponent(setStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonInsert)
                            .addComponent(buttonUpdate)
                            .addComponent(buttonDelete)
                            .addComponent(buttonReset))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertActionPerformed
        // TODO add your handling code here:
        mhc.insert();
        mhc.isiTable();
        mhc.reset();
    }//GEN-LAST:event_buttonInsertActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
        mhc.update();
        mhc.isiTable();
        mhc.reset();
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        mhc.delete();
        mhc.isiTable();
        mhc.reset();
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        mhc.reset();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonCariNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariNamaActionPerformed
        // TODO add your handling code here:
        mhc.cariNama();
    }//GEN-LAST:event_buttonCariNamaActionPerformed

    private void buttonPilihFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPilihFotoActionPerformed
        // TODO add your handling code here:
        byte[] foto = ph.fotoKeByte();
        fotoHewan.setIcon(ph.byteKeIcon(foto, 100, 100));
        fotoHewan.setText("");
        
    }//GEN-LAST:event_buttonPilihFotoActionPerformed

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        // TODO add your handling code here:
        mhc.refresh();
    }//GEN-LAST:event_buttonRefreshActionPerformed

    private void txtCariNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCariNamaFocusGained
        // TODO add your handling code here:
        txtCariNama.setText("");
    }//GEN-LAST:event_txtCariNamaFocusGained

    private void txtCariNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCariNamaFocusLost
        // TODO add your handling code here:
        txtCariNama.setText("nama hewan...");
    }//GEN-LAST:event_txtCariNamaFocusLost

    private void buttonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDashboardActionPerformed
        // TODO add your handling code here:
        this.dispose();
        dav = new DashboardAdminView();
        dav.setVisible(true);
    }//GEN-LAST:event_buttonDashboardActionPerformed

    private void buttonManajemenAdopsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManajemenAdopsiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        mav = new ManajemenAdopsi();
        mav.setVisible(true);
    }//GEN-LAST:event_buttonManajemenAdopsiActionPerformed

    private void buttonRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRiwayatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        rav = new RiwayatAdopsiView();
        rav.setVisible(true);
    }//GEN-LAST:event_buttonRiwayatActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCariNama;
    private javax.swing.JButton buttonDashboard;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonInsert;
    private javax.swing.JButton buttonManajemenAdopsi;
    private javax.swing.JButton buttonManajemenHewan;
    private javax.swing.JButton buttonPilihFoto;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonRiwayat;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JLabel fotoHewan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulBulan;
    private javax.swing.JLabel judulDeskripsi;
    private javax.swing.JLabel judulFoto;
    private javax.swing.JLabel judulHalaman;
    private javax.swing.JLabel judulID;
    private javax.swing.JLabel judulJenis;
    private javax.swing.JLabel judulKelamin;
    private javax.swing.JLabel judulNama;
    private javax.swing.JLabel judulSearch;
    private javax.swing.JLabel judulStatus;
    private javax.swing.JLabel judulUmur;
    private javax.swing.JComboBox<String> setJenis;
    private javax.swing.JComboBox<String> setKelamin;
    private javax.swing.JComboBox<String> setStatus;
    private javax.swing.JTable tabelData;
    private javax.swing.JLabel titikDua1;
    private javax.swing.JLabel titikDua2;
    private javax.swing.JLabel titikDua3;
    private javax.swing.JLabel titikDua4;
    private javax.swing.JLabel titikDua5;
    private javax.swing.JLabel titikDua6;
    private javax.swing.JLabel titikDua7;
    private javax.swing.JLabel titikDua8;
    private javax.swing.JTextField txtCariNama;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
    
    public JTextField getTxtCariNama() {
        return txtCariNama;
    }
    
    public JTextField getTxtDeskripsi() {
        return txtDeskripsi;
    }
    
    public JTextField getTxtID() {
        return txtID;
    }
    
    public JTextField getTxtNama() {
        return txtNama;
    }
    
    public JTextField getTxtUmur() {
        return txtUmur;
    }
    
    public JComboBox getTxtJenis() {
        return setJenis;
    }
    
    public JComboBox getTxtKelamin() {
        return setKelamin;
    }
    
    public JComboBox getTxtStatus() {
        return setStatus;
    }
    
    public JTable getTabelData() {
        return tabelData;
    }
    
    public JButton getButtonInsert() {
        return buttonInsert;
    }
    
    public JButton getButtonUpdate() {
        return buttonUpdate;
    }
    
    public JButton getButtonDelete() {
        return buttonDelete;
    }
    
    public JButton getButtonCari() {
        return buttonCariNama;
    }
    
    public JLabel getFotoHewan() {
        return fotoHewan;
    }
    
}
